layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: date
  sort_by options:
     - pushed
  #   - stars
  limit: 6
  exclude:
    archived: true
    forks: true
    projects:
#      - uber-pickups-data-analysis
#      - Tic-Tac-Toe
#      - SQLite-Python-DataInserting
#      - 210CT-Coursework
#      - BinarySeach-vs-LinearSearch

social_media:
  email: mailto:princesoonam@gmail.com
  # behance: your_username
  # dribbble: your_username
  #facebook: soonam
  #hackerrank: soonam
  #instagram: soonam
  keybase: soonam
  linkedin: soonam-kalyan-panda
  # mastodon: your_username
  #medium: soonam
  stackoverflow: 7693704
  # telegram: your_username
  twitter: soonamkalyan
  # unsplash: your_username
  # vk: your_username
  #youtube: soonam

topics:
  - name: Azure
    web_url: https://github.com/topics/azure
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/azure/azure.png

  - name: Amazon Web Services
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kubernetes/kubernetes.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: Terraform
    web_url: https://github.com/topics/terraform
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/terraform/terraform.png

  - name: Airflow
    web_url: https://github.com/topics/airflow
    image_url: https://github.com/apache/airflow/blob/02d22f6ce2dbb4a1c5c5eb01dfa3070327e377bb/images/quick_start/local_airflow.png
