title: Hello, world! I'm Soonam Kalyan
#description: > # this means to ignore newlines until "baseurl:"
 # Write an awesome description for your new site here. You can edit this
 # line in _config.yml. It will appear in your document head meta (for
 # Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://IamSoo.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Soonam Kalyan Panda # add your name
author-img: profile.png # add your photo
about-author: I am a passionate full stack,cloud & bigdata developer. I prefer to do mistake and learn rather sitting quite. # add description
social-facebook: # add your Facebook handle
social-github: iamsoo # add your Github handle
social-linkedin: https://www.linkedin.com/in/soonam-kalyan-panda/ # add your Linkedin handle
social-email: princesoonam@yahoo.co.in # add your Email address
#site-er: #if your site has a twitter account, enter it here

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
